version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3000" # Expose app on 3003 externally, 3000 internally
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  nginx-config:
    image: alpine:latest # Lightweight image for copying files
    volumes:
      - ./nginx.conf:/nginx.conf # Mount the config file from your project
      - /etc/nginx/sites-available:/sites-available # Mount server's sites-available
      - /etc/nginx/sites-enabled:/sites-enabled # Mount server's sites-enabled
    command: >
      sh -c "cp /nginx.conf /sites-available/fadilogic.serp24.online &&
             ln -sf /sites-available/fadilogic.serp24.online /sites-enabled/fadilogic.serp24.online &&
             nginx -t && systemctl reload nginx"
    # This service runs once and exits