version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3003:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    mem_limit: 1G
    mem_reservation: 512M
    cpus: 1.0
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000']
      interval: 10s
      timeout: 5s
      retries: 3

  nginx-config-fadilogic:
    image: alpine:latest
    volumes:
      - ./nginx.conf:/nginx.conf:ro
      - /etc/nginx/sites-available:/sites-available
      - /etc/nginx/sites-enabled:/sites-enabled
    command: >
      sh -c "mkdir -p /sites-available /sites-enabled && 
             cp -f /nginx.conf /sites-available/fadidabboura.com &&
             ln -sf /etc/nginx/sites-available/fadidabboura.com /sites-enabled/fadidabboura.com &&
             ls -l /sites-available/fadidabboura.com &&
             ls -l /sites-enabled/fadidabboura.com"
