version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"  # Limit to 1 CPU core
          memory: "1G"  # Limit to 1GB of RAM
        reservations:
          cpus: "0.5"  # Reserve at least 0.5 CPU cores
          memory: "512M"  # Reserve at least 512MB of RAM

  nginx-config-fadilogic:
    image: alpine:latest
    volumes:
      - ./nginx.conf:/nginx.conf:ro
      - /etc/nginx/sites-available:/sites-available
      - /etc/nginx/sites-enabled:/sites-enabled
    command: >
      sh -c "cp -f /nginx.conf /sites-available/fadilogic.serp24.online &&
             ln -sf /etc/nginx/sites-available/fadilogic.serp24.online /sites-enabled/fadilogic.serp24.online &&
             ls -l /sites-enabled/fadilogic.serp24.online"